### ISSUE TITLE
Show more information on ASR tab

### ISSUE THREAD

**Issue by tsubasaxZZZ** [Azure/reliability-workbook#130]
> For example: Listing all VMs where ASR setup was completed and last operation (state). Did ASR resource replicate to a secondary location? did resource failover via ASR? did resource failback via ASR? Showing also percentages of success/failure ration can help customer to have a better method to measure RPO per resource/workload.

```[tasklist]
### Tasks
- [x] Show replication health(replicationHealth)
- [x] Show failover health(failoverHealth)
- [x] Show status of test failover(lastSuccessfulTestFailoverTime)
- [x] Show protection description(protectionStateDescription)
```

**Comment by tsubasaxZZZ** [comment]
## Show protection description(protectionStateDescription)
After failover before commit:
```
    "currentProtectionState": "UnplannedFailoverCommitPendingStatesBegin",
    "protectionStateDescription": "Failover completed",
```

After failover after commited:
```
    "currentProtectionState": "UnplannedFailoverCommitted",
    "protectionStateDescription": "Failover committed",
```
